name: TranslationApp CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v2
 
    - name: Build TranslationApp
      run: msbuild TranslationApp.sln /t:restore,build /p:RestorePackagesConfig=True /p:Configuration=Debug
      
    - name: Get short SHA
      run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
       
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TranslationApp_${{ env.SHORT_SHA }}
        path: TranslationApp\bin\Debug\
